---
language: ruby

cache:
  - bundler
  - apt

before_install:
  - sudo apt-get update

install: 
  - sudo apt-get install libgpod4-nogtk libgpod-nogtk-dev
  - bundle install

script: bundle exec rake test

rvm:
  - 1.9.3
